//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFZamowienia.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZamowieniaFirmaEntities : DbContext
    {
        public ZamowieniaFirmaEntities()
            : base("name=ZamowieniaFirmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JednostkaMiary> JednostkaMiary { get; set; }
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<PozycjaZamowienia> PozycjaZamowienia { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Towar> Towar { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
    }
}
