//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFZamowienia.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjaZamowienia
    {
        public int IdPozycjiZamowienia { get; set; }
        public Nullable<int> IdZamowienia { get; set; }
        public Nullable<int> IdTowaru { get; set; }
        public Nullable<decimal> Ilosc { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<decimal> Wartosc { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Towar Towar { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
