//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFZamowienia.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienia()
        {
            this.PozycjaZamowienia = new HashSet<PozycjaZamowienia>();
        }
    
        public int IdZamowienia { get; set; }
        public string NrZamowienia { get; set; }
        public Nullable<System.DateTime> DataZamowienia { get; set; }
        public Nullable<System.DateTime> DataRealizacji { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public string Opis { get; set; }
        public Nullable<int> IdPozycjiZamowienia { get; set; }
        public string Status { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Klient Klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaZamowienia> PozycjaZamowienia { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
