//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceZamowienia
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TowarForView", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia")]
    public partial class TowarForView : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private System.Nullable<int> IdJednostkiMiaryField;
        
        private System.Nullable<int> IdKategoriiField;
        
        private int IdTowaruField;
        
        private System.Nullable<decimal> IloscField;
        
        private string JednostkaMiaryNazwaField;
        
        private string KategoriaNazwaField;
        
        private string KodField;
        
        private string NazwaTowaruField;
        
        private string NrKatalogowyField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdJednostkiMiary
        {
            get
            {
                return this.IdJednostkiMiaryField;
            }
            set
            {
                this.IdJednostkiMiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKategorii
        {
            get
            {
                return this.IdKategoriiField;
            }
            set
            {
                this.IdKategoriiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTowaru
        {
            get
            {
                return this.IdTowaruField;
            }
            set
            {
                this.IdTowaruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JednostkaMiaryNazwa
        {
            get
            {
                return this.JednostkaMiaryNazwaField;
            }
            set
            {
                this.JednostkaMiaryNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KategoriaNazwa
        {
            get
            {
                return this.KategoriaNazwaField;
            }
            set
            {
                this.KategoriaNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kod
        {
            get
            {
                return this.KodField;
            }
            set
            {
                this.KodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaTowaru
        {
            get
            {
                return this.NazwaTowaruField;
            }
            set
            {
                this.NazwaTowaruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NrKatalogowy
        {
            get
            {
                return this.NrKatalogowyField;
            }
            set
            {
                this.NrKatalogowyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KlientForView", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia")]
    public partial class KlientForView : object
    {
        
        private string AdresField;
        
        private int IdKlientaField;
        
        private string KodPocztowyField;
        
        private string MiejscowoscField;
        
        private string NazwaField;
        
        private string NipField;
        
        private string TelefonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKlienta
        {
            get
            {
                return this.IdKlientaField;
            }
            set
            {
                this.IdKlientaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodPocztowy
        {
            get
            {
                return this.KodPocztowyField;
            }
            set
            {
                this.KodPocztowyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Miejscowosc
        {
            get
            {
                return this.MiejscowoscField;
            }
            set
            {
                this.MiejscowoscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nip
        {
            get
            {
                return this.NipField;
            }
            set
            {
                this.NipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KategorieForView", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia")]
    public partial class KategorieForView : object
    {
        
        private int IdKategoriiField;
        
        private string NazwaField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKategorii
        {
            get
            {
                return this.IdKategoriiField;
            }
            set
            {
                this.IdKategoriiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZamowieniaForView", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia")]
    public partial class ZamowieniaForView : object
    {
        
        private string CenaField;
        
        private System.Nullable<System.DateTime> DataRealizacjiField;
        
        private System.Nullable<System.DateTime> DataZamowieniaField;
        
        private System.Nullable<int> IdKlientaField;
        
        private System.Nullable<int> IdPozycjiZamowieniaField;
        
        private System.Nullable<int> IdPracownikaField;
        
        private int IdZamowieniaField;
        
        private string KlientDaneField;
        
        private string NazwaField;
        
        private string NrZamowieniaField;
        
        private string OpisField;
        
        private string PozycjaZamowieniaField;
        
        private string PracownikDaneField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRealizacji
        {
            get
            {
                return this.DataRealizacjiField;
            }
            set
            {
                this.DataRealizacjiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataZamowienia
        {
            get
            {
                return this.DataZamowieniaField;
            }
            set
            {
                this.DataZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKlienta
        {
            get
            {
                return this.IdKlientaField;
            }
            set
            {
                this.IdKlientaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPozycjiZamowienia
        {
            get
            {
                return this.IdPozycjiZamowieniaField;
            }
            set
            {
                this.IdPozycjiZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdZamowienia
        {
            get
            {
                return this.IdZamowieniaField;
            }
            set
            {
                this.IdZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KlientDane
        {
            get
            {
                return this.KlientDaneField;
            }
            set
            {
                this.KlientDaneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NrZamowienia
        {
            get
            {
                return this.NrZamowieniaField;
            }
            set
            {
                this.NrZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PozycjaZamowienia
        {
            get
            {
                return this.PozycjaZamowieniaField;
            }
            set
            {
                this.PozycjaZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PracownikDane
        {
            get
            {
                return this.PracownikDaneField;
            }
            set
            {
                this.PracownikDaneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PozycjaZamowieniaForView", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia")]
    public partial class PozycjaZamowieniaForView : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private System.Nullable<int> IdKategoriiField;
        
        private int IdPozycjiZamowieniaField;
        
        private System.Nullable<int> IdTowaruField;
        
        private System.Nullable<int> IdZamowieniaField;
        
        private System.Nullable<decimal> IloscField;
        
        private string KategoriaNazwaField;
        
        private string TowarNazwaField;
        
        private System.Nullable<decimal> WartoscField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKategorii
        {
            get
            {
                return this.IdKategoriiField;
            }
            set
            {
                this.IdKategoriiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPozycjiZamowienia
        {
            get
            {
                return this.IdPozycjiZamowieniaField;
            }
            set
            {
                this.IdPozycjiZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTowaru
        {
            get
            {
                return this.IdTowaruField;
            }
            set
            {
                this.IdTowaruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdZamowienia
        {
            get
            {
                return this.IdZamowieniaField;
            }
            set
            {
                this.IdZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KategoriaNazwa
        {
            get
            {
                return this.KategoriaNazwaField;
            }
            set
            {
                this.KategoriaNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TowarNazwa
        {
            get
            {
                return this.TowarNazwaField;
            }
            set
            {
                this.TowarNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Wartosc
        {
            get
            {
                return this.WartoscField;
            }
            set
            {
                this.WartoscField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klient", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia.Model.Entities")]
    public partial class Klient : object
    {
        
        private string AdresField;
        
        private System.Nullable<bool> CzyAktywnyField;
        
        private int IdKlientaField;
        
        private string KodPocztowyField;
        
        private string MiejscowoscField;
        
        private string NazwaField;
        
        private string NipField;
        
        private string TelefonField;
        
        private System.Collections.Generic.List<ServiceReferenceZamowienia.Zamowienia> ZamowieniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CzyAktywny
        {
            get
            {
                return this.CzyAktywnyField;
            }
            set
            {
                this.CzyAktywnyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKlienta
        {
            get
            {
                return this.IdKlientaField;
            }
            set
            {
                this.IdKlientaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodPocztowy
        {
            get
            {
                return this.KodPocztowyField;
            }
            set
            {
                this.KodPocztowyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Miejscowosc
        {
            get
            {
                return this.MiejscowoscField;
            }
            set
            {
                this.MiejscowoscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nip
        {
            get
            {
                return this.NipField;
            }
            set
            {
                this.NipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.Zamowienia> Zamowienia
        {
            get
            {
                return this.ZamowieniaField;
            }
            set
            {
                this.ZamowieniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zamowienia", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia.Model.Entities")]
    public partial class Zamowienia : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private System.Nullable<bool> CzyAktywnyField;
        
        private System.Nullable<System.DateTime> DataRealizacjiField;
        
        private System.Nullable<System.DateTime> DataZamowieniaField;
        
        private System.Nullable<int> IdKlientaField;
        
        private System.Nullable<int> IdPozycjiZamowieniaField;
        
        private System.Nullable<int> IdPracownikaField;
        
        private int IdZamowieniaField;
        
        private ServiceReferenceZamowienia.Klient KlientField;
        
        private string NazwaField;
        
        private string NrZamowieniaField;
        
        private string OpisField;
        
        private System.Collections.Generic.List<ServiceReferenceZamowienia.PozycjaZamowienia> PozycjaZamowieniaField;
        
        private ServiceReferenceZamowienia.Pracownicy PracownicyField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CzyAktywny
        {
            get
            {
                return this.CzyAktywnyField;
            }
            set
            {
                this.CzyAktywnyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRealizacji
        {
            get
            {
                return this.DataRealizacjiField;
            }
            set
            {
                this.DataRealizacjiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataZamowienia
        {
            get
            {
                return this.DataZamowieniaField;
            }
            set
            {
                this.DataZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKlienta
        {
            get
            {
                return this.IdKlientaField;
            }
            set
            {
                this.IdKlientaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPozycjiZamowienia
        {
            get
            {
                return this.IdPozycjiZamowieniaField;
            }
            set
            {
                this.IdPozycjiZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdZamowienia
        {
            get
            {
                return this.IdZamowieniaField;
            }
            set
            {
                this.IdZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceZamowienia.Klient Klient
        {
            get
            {
                return this.KlientField;
            }
            set
            {
                this.KlientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NrZamowienia
        {
            get
            {
                return this.NrZamowieniaField;
            }
            set
            {
                this.NrZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.PozycjaZamowienia> PozycjaZamowienia
        {
            get
            {
                return this.PozycjaZamowieniaField;
            }
            set
            {
                this.PozycjaZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceZamowienia.Pracownicy Pracownicy
        {
            get
            {
                return this.PracownicyField;
            }
            set
            {
                this.PracownicyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pracownicy", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia.Model.Entities")]
    public partial class Pracownicy : object
    {
        
        private System.Nullable<bool> CzyAktywnyField;
        
        private string HasloField;
        
        private int IdPracownikaField;
        
        private string ImieField;
        
        private string LoginField;
        
        private string NazwaField;
        
        private string NazwiskoField;
        
        private System.Collections.Generic.List<ServiceReferenceZamowienia.Zamowienia> ZamowieniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CzyAktywny
        {
            get
            {
                return this.CzyAktywnyField;
            }
            set
            {
                this.CzyAktywnyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Haslo
        {
            get
            {
                return this.HasloField;
            }
            set
            {
                this.HasloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.Zamowienia> Zamowienia
        {
            get
            {
                return this.ZamowieniaField;
            }
            set
            {
                this.ZamowieniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PozycjaZamowienia", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia.Model.Entities")]
    public partial class PozycjaZamowienia : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private System.Nullable<bool> CzyAktywnyField;
        
        private int IdPozycjiZamowieniaField;
        
        private System.Nullable<int> IdTowaruField;
        
        private System.Nullable<int> IdZamowieniaField;
        
        private System.Nullable<decimal> IloscField;
        
        private ServiceReferenceZamowienia.Towar TowarField;
        
        private System.Nullable<decimal> WartoscField;
        
        private ServiceReferenceZamowienia.Zamowienia ZamowieniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CzyAktywny
        {
            get
            {
                return this.CzyAktywnyField;
            }
            set
            {
                this.CzyAktywnyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPozycjiZamowienia
        {
            get
            {
                return this.IdPozycjiZamowieniaField;
            }
            set
            {
                this.IdPozycjiZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTowaru
        {
            get
            {
                return this.IdTowaruField;
            }
            set
            {
                this.IdTowaruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdZamowienia
        {
            get
            {
                return this.IdZamowieniaField;
            }
            set
            {
                this.IdZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceZamowienia.Towar Towar
        {
            get
            {
                return this.TowarField;
            }
            set
            {
                this.TowarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Wartosc
        {
            get
            {
                return this.WartoscField;
            }
            set
            {
                this.WartoscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceZamowienia.Zamowienia Zamowienia
        {
            get
            {
                return this.ZamowieniaField;
            }
            set
            {
                this.ZamowieniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Towar", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia.Model.Entities")]
    public partial class Towar : object
    {
        
        private System.Nullable<decimal> CenaField;
        
        private System.Nullable<bool> CzyAktywnyField;
        
        private System.Nullable<int> IdJednostkiMiaryField;
        
        private System.Nullable<int> IdKategoriField;
        
        private int IdTowaruField;
        
        private System.Nullable<decimal> IloscField;
        
        private ServiceReferenceZamowienia.JednostkaMiary JednostkaMiaryField;
        
        private ServiceReferenceZamowienia.Kategorie KategorieField;
        
        private string KodField;
        
        private string NazwaTowaruField;
        
        private string NrKatalogowyField;
        
        private string OpisField;
        
        private System.Collections.Generic.List<ServiceReferenceZamowienia.PozycjaZamowienia> PozycjaZamowieniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena
        {
            get
            {
                return this.CenaField;
            }
            set
            {
                this.CenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CzyAktywny
        {
            get
            {
                return this.CzyAktywnyField;
            }
            set
            {
                this.CzyAktywnyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdJednostkiMiary
        {
            get
            {
                return this.IdJednostkiMiaryField;
            }
            set
            {
                this.IdJednostkiMiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKategori
        {
            get
            {
                return this.IdKategoriField;
            }
            set
            {
                this.IdKategoriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTowaru
        {
            get
            {
                return this.IdTowaruField;
            }
            set
            {
                this.IdTowaruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ilosc
        {
            get
            {
                return this.IloscField;
            }
            set
            {
                this.IloscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceZamowienia.JednostkaMiary JednostkaMiary
        {
            get
            {
                return this.JednostkaMiaryField;
            }
            set
            {
                this.JednostkaMiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceZamowienia.Kategorie Kategorie
        {
            get
            {
                return this.KategorieField;
            }
            set
            {
                this.KategorieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kod
        {
            get
            {
                return this.KodField;
            }
            set
            {
                this.KodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaTowaru
        {
            get
            {
                return this.NazwaTowaruField;
            }
            set
            {
                this.NazwaTowaruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NrKatalogowy
        {
            get
            {
                return this.NrKatalogowyField;
            }
            set
            {
                this.NrKatalogowyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.PozycjaZamowienia> PozycjaZamowienia
        {
            get
            {
                return this.PozycjaZamowieniaField;
            }
            set
            {
                this.PozycjaZamowieniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JednostkaMiary", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia.Model.Entities")]
    public partial class JednostkaMiary : object
    {
        
        private System.Nullable<bool> CzyAktywnyField;
        
        private int IdJedostkiMiaryField;
        
        private string NazwaField;
        
        private string OpisField;
        
        private System.Collections.Generic.List<ServiceReferenceZamowienia.Towar> TowarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CzyAktywny
        {
            get
            {
                return this.CzyAktywnyField;
            }
            set
            {
                this.CzyAktywnyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJedostkiMiary
        {
            get
            {
                return this.IdJedostkiMiaryField;
            }
            set
            {
                this.IdJedostkiMiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.Towar> Towar
        {
            get
            {
                return this.TowarField;
            }
            set
            {
                this.TowarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kategorie", Namespace="http://schemas.datacontract.org/2004/07/WCFZamowienia.Model.Entities")]
    public partial class Kategorie : object
    {
        
        private System.Nullable<bool> CzyAktywnyField;
        
        private int IdKategoriiField;
        
        private string NazwaField;
        
        private string OpisField;
        
        private System.Collections.Generic.List<ServiceReferenceZamowienia.Towar> TowarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CzyAktywny
        {
            get
            {
                return this.CzyAktywnyField;
            }
            set
            {
                this.CzyAktywnyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKategorii
        {
            get
            {
                return this.IdKategoriiField;
            }
            set
            {
                this.IdKategoriiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.Towar> Towar
        {
            get
            {
                return this.TowarField;
            }
            set
            {
                this.TowarField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceZamowienia.IServiceZamowienia")]
    public interface IServiceZamowienia
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetData", ReplyAction="http://tempuri.org/IServiceZamowienia/GetDataResponse")]
        ServiceReferenceZamowienia.GetDataResponse GetData(ServiceReferenceZamowienia.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetData", ReplyAction="http://tempuri.org/IServiceZamowienia/GetDataResponse")]
        System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetDataResponse> GetDataAsync(ServiceReferenceZamowienia.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceZamowienia/GetDataUsingDataContractResponse")]
        ServiceReferenceZamowienia.GetDataUsingDataContractResponse GetDataUsingDataContract(ServiceReferenceZamowienia.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceZamowienia/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(ServiceReferenceZamowienia.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetTowary", ReplyAction="http://tempuri.org/IServiceZamowienia/GetTowaryResponse")]
        ServiceReferenceZamowienia.GetTowaryResponse GetTowary(ServiceReferenceZamowienia.GetTowaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetTowary", ReplyAction="http://tempuri.org/IServiceZamowienia/GetTowaryResponse")]
        System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetTowaryResponse> GetTowaryAsync(ServiceReferenceZamowienia.GetTowaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetKlienci", ReplyAction="http://tempuri.org/IServiceZamowienia/GetKlienciResponse")]
        ServiceReferenceZamowienia.GetKlienciResponse GetKlienci(ServiceReferenceZamowienia.GetKlienciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetKlienci", ReplyAction="http://tempuri.org/IServiceZamowienia/GetKlienciResponse")]
        System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetKlienciResponse> GetKlienciAsync(ServiceReferenceZamowienia.GetKlienciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetKategorie", ReplyAction="http://tempuri.org/IServiceZamowienia/GetKategorieResponse")]
        ServiceReferenceZamowienia.GetKategorieResponse GetKategorie(ServiceReferenceZamowienia.GetKategorieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetKategorie", ReplyAction="http://tempuri.org/IServiceZamowienia/GetKategorieResponse")]
        System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetKategorieResponse> GetKategorieAsync(ServiceReferenceZamowienia.GetKategorieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetZamowienia", ReplyAction="http://tempuri.org/IServiceZamowienia/GetZamowieniaResponse")]
        ServiceReferenceZamowienia.GetZamowieniaResponse GetZamowienia(ServiceReferenceZamowienia.GetZamowieniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetZamowienia", ReplyAction="http://tempuri.org/IServiceZamowienia/GetZamowieniaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetZamowieniaResponse> GetZamowieniaAsync(ServiceReferenceZamowienia.GetZamowieniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetPozycjeZamowienia", ReplyAction="http://tempuri.org/IServiceZamowienia/GetPozycjeZamowieniaResponse")]
        ServiceReferenceZamowienia.GetPozycjeZamowieniaResponse GetPozycjeZamowienia(ServiceReferenceZamowienia.GetPozycjeZamowieniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/GetPozycjeZamowienia", ReplyAction="http://tempuri.org/IServiceZamowienia/GetPozycjeZamowieniaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetPozycjeZamowieniaResponse> GetPozycjeZamowieniaAsync(ServiceReferenceZamowienia.GetPozycjeZamowieniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/AddKlient", ReplyAction="http://tempuri.org/IServiceZamowienia/AddKlientResponse")]
        ServiceReferenceZamowienia.AddKlientResponse AddKlient(ServiceReferenceZamowienia.AddKlientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZamowienia/AddKlient", ReplyAction="http://tempuri.org/IServiceZamowienia/AddKlientResponse")]
        System.Threading.Tasks.Task<ServiceReferenceZamowienia.AddKlientResponse> AddKlientAsync(ServiceReferenceZamowienia.AddKlientRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest()
        {
        }
        
        public GetDataRequest(int value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataResult;
        
        public GetDataResponse()
        {
        }
        
        public GetDataResponse(string GetDataResult)
        {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceZamowienia.CompositeType composite;
        
        public GetDataUsingDataContractRequest()
        {
        }
        
        public GetDataUsingDataContractRequest(ServiceReferenceZamowienia.CompositeType composite)
        {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceZamowienia.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse()
        {
        }
        
        public GetDataUsingDataContractResponse(ServiceReferenceZamowienia.CompositeType GetDataUsingDataContractResult)
        {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTowary", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTowaryRequest
    {
        
        public GetTowaryRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTowaryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTowaryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.TowarForView> GetTowaryResult;
        
        public GetTowaryResponse()
        {
        }
        
        public GetTowaryResponse(System.Collections.Generic.List<ServiceReferenceZamowienia.TowarForView> GetTowaryResult)
        {
            this.GetTowaryResult = GetTowaryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKlienci", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKlienciRequest
    {
        
        public GetKlienciRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKlienciResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKlienciResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.KlientForView> GetKlienciResult;
        
        public GetKlienciResponse()
        {
        }
        
        public GetKlienciResponse(System.Collections.Generic.List<ServiceReferenceZamowienia.KlientForView> GetKlienciResult)
        {
            this.GetKlienciResult = GetKlienciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKategorie", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKategorieRequest
    {
        
        public GetKategorieRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKategorieResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKategorieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.KategorieForView> GetKategorieResult;
        
        public GetKategorieResponse()
        {
        }
        
        public GetKategorieResponse(System.Collections.Generic.List<ServiceReferenceZamowienia.KategorieForView> GetKategorieResult)
        {
            this.GetKategorieResult = GetKategorieResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetZamowienia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetZamowieniaRequest
    {
        
        public GetZamowieniaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetZamowieniaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetZamowieniaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.ZamowieniaForView> GetZamowieniaResult;
        
        public GetZamowieniaResponse()
        {
        }
        
        public GetZamowieniaResponse(System.Collections.Generic.List<ServiceReferenceZamowienia.ZamowieniaForView> GetZamowieniaResult)
        {
            this.GetZamowieniaResult = GetZamowieniaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPozycjeZamowienia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPozycjeZamowieniaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idZamowienia;
        
        public GetPozycjeZamowieniaRequest()
        {
        }
        
        public GetPozycjeZamowieniaRequest(int idZamowienia)
        {
            this.idZamowienia = idZamowienia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPozycjeZamowieniaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPozycjeZamowieniaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceZamowienia.PozycjaZamowieniaForView> GetPozycjeZamowieniaResult;
        
        public GetPozycjeZamowieniaResponse()
        {
        }
        
        public GetPozycjeZamowieniaResponse(System.Collections.Generic.List<ServiceReferenceZamowienia.PozycjaZamowieniaForView> GetPozycjeZamowieniaResult)
        {
            this.GetPozycjeZamowieniaResult = GetPozycjeZamowieniaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddKlient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddKlientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceZamowienia.Klient klient;
        
        public AddKlientRequest()
        {
        }
        
        public AddKlientRequest(ServiceReferenceZamowienia.Klient klient)
        {
            this.klient = klient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddKlientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddKlientResponse
    {
        
        public AddKlientResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceZamowieniaChannel : ServiceReferenceZamowienia.IServiceZamowienia, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceZamowieniaClient : System.ServiceModel.ClientBase<ServiceReferenceZamowienia.IServiceZamowienia>, ServiceReferenceZamowienia.IServiceZamowienia
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceZamowieniaClient() : 
                base(ServiceZamowieniaClient.GetDefaultBinding(), ServiceZamowieniaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceZamowienia.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceZamowieniaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceZamowieniaClient.GetBindingForEndpoint(endpointConfiguration), ServiceZamowieniaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceZamowieniaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceZamowieniaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceZamowieniaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceZamowieniaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceZamowieniaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReferenceZamowienia.GetDataResponse GetData(ServiceReferenceZamowienia.GetDataRequest request)
        {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetDataResponse> GetDataAsync(ServiceReferenceZamowienia.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public ServiceReferenceZamowienia.GetDataUsingDataContractResponse GetDataUsingDataContract(ServiceReferenceZamowienia.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(ServiceReferenceZamowienia.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public ServiceReferenceZamowienia.GetTowaryResponse GetTowary(ServiceReferenceZamowienia.GetTowaryRequest request)
        {
            return base.Channel.GetTowary(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetTowaryResponse> GetTowaryAsync(ServiceReferenceZamowienia.GetTowaryRequest request)
        {
            return base.Channel.GetTowaryAsync(request);
        }
        
        public ServiceReferenceZamowienia.GetKlienciResponse GetKlienci(ServiceReferenceZamowienia.GetKlienciRequest request)
        {
            return base.Channel.GetKlienci(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetKlienciResponse> GetKlienciAsync(ServiceReferenceZamowienia.GetKlienciRequest request)
        {
            return base.Channel.GetKlienciAsync(request);
        }
        
        public ServiceReferenceZamowienia.GetKategorieResponse GetKategorie(ServiceReferenceZamowienia.GetKategorieRequest request)
        {
            return base.Channel.GetKategorie(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetKategorieResponse> GetKategorieAsync(ServiceReferenceZamowienia.GetKategorieRequest request)
        {
            return base.Channel.GetKategorieAsync(request);
        }
        
        public ServiceReferenceZamowienia.GetZamowieniaResponse GetZamowienia(ServiceReferenceZamowienia.GetZamowieniaRequest request)
        {
            return base.Channel.GetZamowienia(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetZamowieniaResponse> GetZamowieniaAsync(ServiceReferenceZamowienia.GetZamowieniaRequest request)
        {
            return base.Channel.GetZamowieniaAsync(request);
        }
        
        public ServiceReferenceZamowienia.GetPozycjeZamowieniaResponse GetPozycjeZamowienia(ServiceReferenceZamowienia.GetPozycjeZamowieniaRequest request)
        {
            return base.Channel.GetPozycjeZamowienia(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceZamowienia.GetPozycjeZamowieniaResponse> GetPozycjeZamowieniaAsync(ServiceReferenceZamowienia.GetPozycjeZamowieniaRequest request)
        {
            return base.Channel.GetPozycjeZamowieniaAsync(request);
        }
        
        public ServiceReferenceZamowienia.AddKlientResponse AddKlient(ServiceReferenceZamowienia.AddKlientRequest request)
        {
            return base.Channel.AddKlient(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceZamowienia.AddKlientResponse> AddKlientAsync(ServiceReferenceZamowienia.AddKlientRequest request)
        {
            return base.Channel.AddKlientAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceZamowienia))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceZamowienia))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.4:56451/ServiceZamowienia.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceZamowieniaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceZamowienia);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceZamowieniaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceZamowienia);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceZamowienia,
        }
    }
}
